language: python

python:
  - "2.7"

services:
  - mysql

install:
  - pip install -r despliegue/requirements.txt

before_install:
  - mysql -e 'DROP DATABASE IF EXISTS votaciones_splc'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS votaciones_splc;'  
  - mysql -u root --default-character-set=utf8 votaciones_splc < despliegue/database/db_dump/01_script_create_votaciones_splc.sql
  - mysql -u root --default-character-set=utf8 votaciones_splc < despliegue/database/db_dump/02_script_populate_votaciones_splc.sql

script:
  - controllers.py

